# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-17 10:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='desc',
            field=models.TextField(max_length=2000),
        ),
    ]
